---
- name: Set apk repositories
  ansible.builtin.copy:
    src: apk/repositories
    dest: /etc/apk/repositories
    mode: preserve

- name: Install Docker
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
  notify: Enable docker service

- name: Install CoreDNS
  ansible.builtin.package:
    name: coredns
  notify:
    - Enable coredns service
    - Disable resolv.conf DHCP overwrite
    - Update resolv.conf

- name: Configure CoreDNS
  ansible.builtin.copy:
    src: coredns/Corefile
    dest: /etc/coredns/Corefile
    mode: preserve
  notify: Restart coredns service

- name: Install FUSE
  ansible.builtin.package:
    name: fuse
  notify: Enable fuse module

- name: Install logrotate
  ansible.builtin.package:
    name: logrotate
  notify: Enable crond service

- name: Disable sshd password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: Restart sshd service

- name: Add mount propagation fix
  ansible.builtin.copy:
    content: mount --make-shared /
    dest: /etc/local.d/mount-propagation.start
    mode: "0755"
  notify: Enable local service
