---
- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - drill
      - fish
      - htop
      - procps
      - ranger
      - shadow
      - vim
      - wireguard-tools

- name: Set default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/fish

- name: Create .config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - ~/.config/htop

- name: Add htoprc
  ansible.builtin.get_url:
    url: https://git.odrling.xyz/odrling/dotfiles/raw/branch/master/.config/htop/htoprc
    dest: ~/.config/htop/htoprc
    mode: "0600"
