tcp:
  routers:
    nanak8s:
      entryPoints:
        - "websecure"
      rule: "HostSNIRegexp(`^(.+\\.)?japan7\\.bde\\.enseeiht\\.fr$`)"
      service: "nanak8s-file"
      tls:
        passthrough: true
  services:
    nanak8s-file:
      loadBalancer:
        servers:
          - address: "host.docker.internal:8443"
