---
- name: Install packages
  ansible.builtin.package:
    name:
      - curl
      - jq
      - yq

- name: Enable modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - nfs
    - nfsd

- name: Enable sshd tcp forwarding
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?AllowTcpForwarding"
    line: "AllowTcpForwarding yes"
  notify: Restart sshd service

- name: Add nanak8s updater
  ansible.builtin.copy:
    content: "{{ lookup('community.sops.sops', 'periodic/nanak8s.sops.sh') }}"
    dest: /etc/periodic/15min/nanak8s
    mode: "0755"
  notify: Enable crond service

- name: Add garage updater
  ansible.builtin.copy:
    src: periodic/garage.sh
    dest: /etc/periodic/15min/garage
    mode: preserve
