services:
  files:
    image: rclone/rclone:1.66.0
    command: serve http $RCLONE_REMOTE --addr :8080 --template /config/rclone/index.html --verbose
    volumes:
      - ../shared/rclone:/config/rclone
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.files.entrypoints=websecure
      - traefik.http.routers.files.middlewares=cache-control-private@docker,japan7-basic@docker
      - traefik.http.services.files-docker.loadbalancer.server.port=8080

  projo:
    image: svenstaro/miniserve:0.27.0-alpine
    command: /html
    volumes:
      - $PROJO_HOST_MOUNT:/html:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.projo.entrypoints=websecure
      - traefik.http.routers.projo.middlewares=cache-control-private@docker,japan7-basic@docker
      - traefik.http.services.projo-docker.loadbalancer.server.port=8080

  projo-dl:
    image: python:3.12.3-alpine
    hostname: $PROJO_HOSTNAME
    entrypoint: crond -f
    volumes:
      - $PROJO_HOST_MOUNT:/projo
      - ./projo:/etc/periodic/hourly:ro
    restart: unless-stopped

  rclone-nfs:
    build: rclone-nfs
    environment:
      - RCLONE_REMOTE=$RCLONE_NFS_REMOTE
      - RCLONE_OPTS=--transfers 50 --checkers 100 --vfs-cache-max-age 15m --vfs-write-back 5m
      - NFS_DISABLE_VERSION_3=1
      - NFS_LOG_LEVEL=DEBUG
    volumes:
      - ../shared/rclone:/config/rclone
      - rclone-nfs-cache:/cache
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.rclone-nfs.entrypoints=rclone-nfs
      - traefik.tcp.routers.rclone-nfs.rule=HostSNI(`*`)
      - traefik.tcp.routers.rclone-nfs.middlewares=rclone-nfs-ipallowlist@docker
      - traefik.tcp.services.rclone-nfs-docker.loadbalancer.server.port=2049
      - traefik.tcp.middlewares.rclone-nfs-ipallowlist.ipallowlist.sourcerange=$RCLONE_NFS_IP_ALLOWLIST
      - com.centurylinklabs.watchtower.enable=false

  # aoc:
  #   image: denoland/deno:alpine
  #   command:
  #     - run
  #     - -A
  #     - /app/main.ts
  #   volumes:
  #     - ./.volumes/aoc:/app
  #   restart: unless-stopped
  #   labels:
  #     - com.centurylinklabs.watchtower.enable=false

volumes:
  rclone-nfs-cache:
