---
- name: Base configuration
  hosts: all
  roles:
    - common

- name: Camp configuration
  hosts: camp
  roles:
    - camp

- name: Nadeshiko configuration
  hosts: nadeshiko
  roles:
    - nadeshiko
