---
- name: Configure
  hosts: config
  tags: config
  tasks:
    - name: Camp configuration
      ansible.builtin.include_role:
        name: camp
      when: inventory_hostname == 'camp.yuru.moe'

    - name: Nadeshiko configuration
      ansible.builtin.include_role:
        name: nadeshiko
      when: inventory_hostname == 'nadeshiko.yuru.moe'

- name: Compose
  hosts: compose
  tags: compose
  roles:
    - compose
