services:
  keycloak:
    image: bitnami/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN_USER=$KEYCLOAK_ADMIN_USER
      - KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
      - KEYCLOAK_DATABASE_HOST=keycloak-postgres
      - KEYCLOAK_DATABASE_NAME=postgres
      - KEYCLOAK_DATABASE_USER=$POSTGRES_USER
      - KEYCLOAK_DATABASE_PASSWORD=$POSTGRES_PASSWORD
      - KEYCLOAK_PRODUCTION=true
      - KEYCLOAK_PROXY=edge
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.entrypoints=websecure
      - traefik.http.services.keycloak-docker.loadbalancer.server.port=8080

  keycloak-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./.volumes/keycloak-postgres:/var/lib/postgresql/data
    restart: unless-stopped
