services:
  mastodon:
    image: lscr.io/linuxserver/mastodon:glitch
    environment:
      - LOCAL_DOMAIN=$DOMAIN
      - WEB_DOMAIN=mastodon.$DOMAIN
      - SINGLE_USER_MODE=true
      - SECRET_KEY_BASE=$MASTODON_SECRET_KEY_BASE
      - OTP_SECRET=$MASTODON_OTP_SECRET
      - VAPID_PRIVATE_KEY=$MASTODON_VAPID_PRIVATE_KEY
      - VAPID_PUBLIC_KEY=$MASTODON_VAPID_PUBLIC_KEY
      - DB_HOST=mastodon-postgres
      - DB_NAME=postgres
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
      - REDIS_HOST=mastodon-redis
      - SMTP_SERVER=$SMTP_HOST
      - SMTP_PORT=$SMTP_PORT
      - SMTP_LOGIN=$SMTP_USERNAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - SMTP_FROM_ADDRESS=mastodon@$DOMAIN
      - SIDEKIQ_THREADS=1
      - WEB_CONCURRENCY=1
      - MAX_THREADS=10
    volumes:
      - ./.volumes/mastodon:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mastodon.entrypoints=websecure
      - traefik.http.services.mastodon-docker.loadbalancer.server.port=443
      # https://docs.linuxserver.io/faq#strict-proxy
      - traefik.http.services.mastodon-docker.loadbalancer.serverstransport=ignorecert@file
      - traefik.http.services.mastodon-docker.loadbalancer.server.scheme=https
      - traefik.http.routers.mastodon-webfinger.entrypoints=websecure
      - traefik.http.routers.mastodon-webfinger.rule=Host(`$DOMAIN`) && Path(`/.well-known/webfinger`)
      - traefik.http.routers.mastodon-webfinger.service=mastodon-docker

  mastodon-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./.volumes/mastodon-postgres:/var/lib/postgresql/data
    restart: unless-stopped

  mastodon-redis:
    image: redis:alpine
    restart: unless-stopped
